#%RAML 1.0 Library

traits:
  transactionId: !include headers-transactionId.raml
  Accept: !include headers-Accept.raml
  language: !include headers-language.raml
  accountNumber: !include queryParams-accountNumbertrait.raml